version: 0.2

phases:
  install:
    commands:
     - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - CURRENT_ENVIRONMENT=`echo $CODEBUILD_INITIATOR | cut -d '-' -f2 | tr '[:upper:]' '[:lower:]'`
      - echo "My env is $CURRENT_ENVIRONMENT"
      - echo "My CODEBUILD_INITIATOR is $CODEBUILD_INITIATOR"
      - echo "Entire environment"
      - printenv
      - echo Find locations of useful files for future reference
      - find . -name "*"
      - /usr/bin/openjml -progress -timeout=36000 -esc -spec-math=bigint -code-math=safe -minQuant -no-staticInitWarning -Werror -prover z3_4_3 ./code/AddLoop.java
  post_build:
    commands:
      - echo Build completed on `date`
      - touch ./sample_output.txt
artifacts:
  files:
    - ./sample_output.txt